version: '3.8'

services:
  # Development service
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    command: npm run dev

  # Production service
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    command: npm start
